{{- if .Values.local_storage.enabled -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: umee-node-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: umee-local-storage
  resources:
    requests:
      storage: {{ $.Values.local_storage.capacity }}
{{- end }}
