{{- if .Values.validator.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: umee-node-config-bootstrap
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "umee-node.labels" . | nindent 4 }}
data:
  init.sh: |
    #!/bin/bash
    set -x
    if [ ! -d "$UMEE_HOME/data" ] 
    then
      umeed init validator $UMEE_MONIKER --home $UMEE_HOME
      cp /bootstrap/genesis.json $UMEE_HOME/config/genesis.json
      cp /bootstrap/priv_validator_key.json $UMEE_HOME/config/priv_validator_key.json
      cp /bootstrap/node_key.json $UMEE_HOME/config/node_key.json
    fi
    apt update && apt install curl -y
    rm -f $UMEE_HOME/config/addrbook.json
    echo '{"height":"0","round":0,"step":0}' > $UMEE_HOME/data/priv_validator_state.json
    /bin/umeed start
    if $UMEE_DEBUG == "true"; then sleep 5000; fi
{{- end }}
