{{- if .Values.fullnode.enabled -}}
---
apiVersion: v1
kind: Service
metadata:
  name: umee-fullnode
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 1317
      name: umee-api
    - port: 9090
      name: umee-grpc
    - port: 26656
      name: umee-p2p
    - port: 26657
      name: umee-rpc
  selector:
    umee.network/fullnode: "{{ .Values.umee_node.moniker }}"
{{- end }}